[wokwi]
version = 1
elf = ".pio/build/adafruit_feather_esp32s3_tft/firmware.elf"
firmware = ".pio/build/adafruit_feather_esp32s3_tft/firmware.bin"

[[net.forward]]
# Forward serial port for monitoring
host = "localhost"
port = 4000
